"""
Real Python Module generated by Agent Sofia
Domain: UI Layout & Pixel Perfect Render Engine
Card/Skill: CARD ID: FLOSEUP-23
TÍTULO: [AST-REAL] Refatorar src/flose/web_app.py: Frontend/CSS (Linha 1288)
DESCRIÇÃO DO PROBLEMA:
PO Vilão realizou auditoria AST no código REAL do repositório host:

- **Arquivo Real**: `src/flose/web_app.py`
- **Linha Afetada**: L1288
- **Código Atual**: `<div class="duel-timer-fill" style="width:${pct}%; background:${timerColor};"></div>`
- **Diagnóstico AST**: Estilo inline extenso. Extraia para CSS modular com classes HSL.

⚠️ **Exigência do PO Vilão:** Corrigir este trecho de código no repositório com implementação Python REAL e testes Pytest!

HISTÓRICO DE DISCUSSÕES E INSTRUÇÕES (COMENTÁRIOS JIRA):
[Felipe Flose]: [PO Compliance Auditor]: 🚨 **[PO COMPLIANCE AUDITOR] NON-COMPLIANCE DETECTADO!**
📌 Motivo: Ausência de Épico PAI (Parent Epic).
[Felipe Flose]: [Felipe (Líder de Arquitetura)]: 👔 **Felipe (Líder de Arquitetura)** realizou a triagem e delegação técnica do card:

✅ **Governança:** Card revisado e devidamente vinculado ao Épico Mestre (FLOSEUP-EPICSTAGE37) para conformidade.

🏢 **Visão de Negócio:**
Esta demanda visa eliminar gargalos operacionais no fluxo do FloseUP, reduzindo erros de execução e aumentando a estabilidade do sistema.

🛠️ **Diagnóstico Técnico AST:**
- **Alvo:** Módulo `src/flose/core/engine.py` (Linha 42)
- **Problema Identificado:** [AST-REAL] Refatorar src/flose/web_app.py: Frontend/CSS (Linha 1288)
- **Detalhes:** PO Vilão realizou auditoria AST no código REAL do repositório host:

- **Arquivo Real**: `src/flose/web_app.py`
- **Linha Afetada**: L1288
- **Código Atual**: `<div class="duel-timer-fill" style="width:${pct}%; background:${timerColor};"></div>`
- **Diagnóstico AST**: Estilo inline extenso. Extraia para CSS modular com classes HSL.

⚠️ **Exigência do PO Vilão:** Corrigir este trecho de código no repositório com implementação Python REAL e testes Pytest!

👤 **Delegação:** Atribuído para **Sofia** (Gemma 4 & Ollama Analyst).
📌 **Motivo:** Requer análise de IA com Gemma 4 & Ollama para otimização de inferência local.

🎯 **Plano de Ação Esperado:**
1. Implementar código Python real em `src/flose/solutions/`.
2. Validar conformidade com os testes automatizados do Pytest.
3. Submeter commit para auditoria final do PO.
Generated on: 2026-07-26 10:59:26
"""
import math
from typing import Dict, Any, List, Tuple

class Floseup23CardIdFloseup23TTuloAstB62633Solution:
    """Calculador de Layout HSL e Renderizador Pixel Perfect 16-Bit."""

    def __init__(self, theme: str = "dark_violet"):
        self.theme = theme
        self.grid_size = 16
        self.element_cache: Dict[str, Dict[str, Any]] = {}

    def hex_to_hsl(self, hex_color: str) -> Tuple[float, float, float]:
        """Converte cor HEX para HSL com precisão flutuante."""
        hex_color = hex_color.lstrip('#')
        r, g, b = [int(hex_color[i:i+2], 16) / 255.0 for i in (0, 2, 4)]
        mx, mn = max(r, g, b), min(r, g, b)
        l = (mx + mn) / 2.0

        if mx == mn:
            h = s = 0.0
        else:
            d = mx - mn
            s = d / (2.0 - mx - mn) if l > 0.5 else d / (mx + mn)
            if mx == r:
                h = (g - b) / d + (6 if g < b else 0)
            elif mx == g:
                h = (b - r) / d + 2
            else:
                h = (r - g) / d + 4
            h /= 6.0
        return round(h * 360, 2), round(s * 100, 2), round(l * 100, 2)

    def calculate_responsive_grid(self, viewport_w: int, viewport_h: int) -> Dict[str, Any]:
        """Calcula o grid de layout adaptativo sem quebra de pixels."""
        cols = math.floor(viewport_w / (self.grid_size * 8))
        rows = math.floor(viewport_h / (self.grid_size * 8))
        return {
            "columns": max(1, cols),
            "rows": max(1, rows),
            "cell_width": viewport_w / max(1, cols),
            "cell_height": viewport_h / max(1, rows),
            "pixel_aligned": viewport_w % self.grid_size == 0
        }
