"""
Real Python Module generated by Agent Beatriz
Domain: UI Layout & Pixel Perfect Render Engine
Card/Skill: ONBOARDING SUBST: Novo colaborador Marcelo Augusto Silva para substituir Mateus Augusto Silva
Generated on: 2026-07-25 20:00:11
"""
import math
from typing import Dict, Any, List, Tuple

class Kan9922OnboardingSubstNovoColaboraE32abdSolution:
    """Calculador de Layout HSL e Renderizador Pixel Perfect 16-Bit."""

    def __init__(self, theme: str = "dark_violet"):
        self.theme = theme
        self.grid_size = 16
        self.element_cache: Dict[str, Dict[str, Any]] = {}

    def hex_to_hsl(self, hex_color: str) -> Tuple[float, float, float]:
        """Converte cor HEX para HSL com precisão flutuante."""
        hex_color = hex_color.lstrip('#')
        r, g, b = [int(hex_color[i:i+2], 16) / 255.0 for i in (0, 2, 4)]
        mx, mn = max(r, g, b), min(r, g, b)
        l = (mx + mn) / 2.0

        if mx == mn:
            h = s = 0.0
        else:
            d = mx - mn
            s = d / (2.0 - mx - mn) if l > 0.5 else d / (mx + mn)
            if mx == r:
                h = (g - b) / d + (6 if g < b else 0)
            elif mx == g:
                h = (b - r) / d + 2
            else:
                h = (r - g) / d + 4
            h /= 6.0
        return round(h * 360, 2), round(s * 100, 2), round(l * 100, 2)

    def calculate_responsive_grid(self, viewport_w: int, viewport_h: int) -> Dict[str, Any]:
        """Calcula o grid de layout adaptativo sem quebra de pixels."""
        cols = math.floor(viewport_w / (self.grid_size * 8))
        rows = math.floor(viewport_h / (self.grid_size * 8))
        return {
            "columns": max(1, cols),
            "rows": max(1, rows),
            "cell_width": viewport_w / max(1, cols),
            "cell_height": viewport_h / max(1, rows),
            "pixel_aligned": viewport_w % self.grid_size == 0
        }
